### ISSUE TITLE
 TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by BlackStoneOfficial** [UsergeTeam/Userge-Assistant#28]
On python 3.8.5, this error occours on any commands related to _is_admin_or_dev()

Here are the logs:
2021-02-01 11:11:32,330 - pyrogram.dispatcher - ERROR - argument of type 'int' is not iterable
2021-02-01T11:11:32.331076+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-01T11:11:32.331077+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 194, in handler_worker
2021-02-01T11:11:32.331077+00:00 app[worker.1]:     if await handler.check(self.client, parsed_update):
2021-02-01T11:11:32.331078+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/handlers/handler.py", line 35, in check
2021-02-01T11:11:32.331078+00:00 app[worker.1]:     return await self.filters(client, update)
2021-02-01T11:11:32.331079+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/filters.py", line 78, in __call__
2021-02-01T11:11:32.331079+00:00 app[worker.1]:     y = await self.other(client, update)
2021-02-01T11:11:32.331079+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/filters.py", line 47, in __call__
2021-02-01T11:11:32.331080+00:00 app[worker.1]:     x = await self.base(client, update)
2021-02-01T11:11:32.331080+00:00 app[worker.1]:   File "/app/assistant/cus_filters.py", line 28, in _is_admin_or_dev
2021-02-01T11:11:32.331080+00:00 app[worker.1]:     if msg.from_user.id in Config.DEV_USERS:
2021-02-01T11:11:32.331081+00:00 app[worker.1]: TypeError: argument of type 'int' is not iterable

**Comment by SpEcHiDe** [comment]
![Uploading IMG_20210201_165320_669.jpg…]()

https://github.com/UsergeTeam/Userge-Assistant/blob/master/assistant/config.py#L30

Check difference between List and int 🤔😐😐

**Comment by BlackStoneOfficial** [comment]
> https://github.com/UsergeTeam/Userge-Assistant/blob/master/assistant/config.py#L30
> 
> Check difference between List and int 🤔😐😐

Ask the script, I didn't change anything on it.
That's definitely a issue

**Comment by Krishna-Singhal** [comment]
https://t.me/UserGeSpam/197357
